In [78]:
import numpy as np
import cv2
import pytesseract
from PIL import Image

In [119]:
img1 = cv2.imread('formexample6.png')
img = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
img = cv2.bitwise_not(img)
img_bin,ab = cv2.threshold(img, 80, 255, cv2.THRESH_BINARY)
cv2.imwrite("RESULT2.jpg",ab)

True

In [120]:
horizontal = np.copy(ab)
# Specify size on horizontal axis
cols = horizontal.shape[1]
horizontal_size = cols // 30
# Create structure element for extracting horizontal lines through morphology operations
horizontalStructure = cv2.getStructuringElement(cv2.MORPH_RECT, (horizontal_size, 1))
    # Apply morphology operations
horizontal = cv2.erode(horizontal, horizontalStructure)
horizontal = cv2.dilate(horizontal, horizontalStructure)
# Show extracted horizontal lines
cv2.imwrite("RESULT3.jpg",horizontal)

True

In [121]:
vertical = np.copy(ab)
# Specify size on vertical axis
rows = vertical.shape[0]
verticalsize = rows // 60
    # Create structure element for extracting vertical lines through morphology operations
verticalStructure = cv2.getStructuringElement(cv2.MORPH_RECT, (1, verticalsize))
    # Apply morphology operations
vertical = cv2.erode(vertical, verticalStructure)
vertical = cv2.dilate(vertical, verticalStructure)
ch = vertical | horizontal
ch = cv2.bitwise_not(ch)
cv2.imwrite("RESULT3.jpg",ch)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [123]:
contours, hierarchy = cv2.findContours(ch, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
img2 = np.copy(img1)
for c in contours:
        x, y, w, h = cv2.boundingRect(c)
        if w > 2*h and w<img2.shape[1]//2 and w>10 and h>5:
          cv2.rectangle(img2, (x, y), (x+w, y+h), (255, 255, 255), -1)
cv2.imwrite("RESULT4.jpg",img2)
cv2.imshow("IMAGE",img2)
cv2.waitKey(0)

-1